services:
  spring:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    container_name: spring
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres:16.3
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: DKdb
    ports:
      - "5433:5432"
    volumes:
      - pgsql_data:/var/lib/postgresql/data

volumes:
  pgsql_data:
    driver: local
